@varBaseUrl = http://localhost
@varBaseUrlPort = {{varBaseUrl}}:5000

###
GET {{varBaseUrlPort}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWEiOiJlcnN5YWQiLCJlbWFpbCI6ImVyc3lhZEBtYWlsLmNvbSIsImlhdCI6MTY1MjgxNDczNywiZXhwIjoxNjUyODE0NzU3fQ.cg16tb_gPqwpMzzLK1gsQrdbVQXdCCISBFYhlkxzMWQ

###
GET {{varBaseUrlPort}}/user_levels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWEiOiJlcnN5YWQiLCJlbWFpbCI6ImVyc3lhZEBtYWlsLmNvbSIsImlhdCI6MTY1MjgxNDczNywiZXhwIjoxNjUyODE0NzU3fQ.cg16tb_gPqwpMzzLK1gsQrdbVQXdCCISBFYhlkxzMWQ

### 
POST {{varBaseUrlPort}}/login
Content-Type: application/json

{
    "email" : "ersyad@mail.com",
    "password" : "666666"
}

###
GET  {{varBaseUrlPort}}/token

###
DELETE {{varBaseUrlPort}}/logout

###
# ini proposal
###
###
GET {{varBaseUrlPort}}/proposals

###
GET {{varBaseUrlPort}}/proposals/2

###
POST {{varBaseUrlPort}}/proposals
Content-Type: application/json

{
    "event_name": "Test event 2",
    "vendor_id": 4,
    "event_date": "2022-01-01",
    "event_date2": "2022-02-02",
    "event_date3": "2022-03-03",
    "event_location": "sambu",
    "status": 0,
    "created_by": 2
}

###
PATCH {{varBaseUrlPort}}/proposals/3
Content-Type: application/json

{
    "title": "Produk 8",
    "price": 999
}

###
DELETE  {{varBaseUrlPort}}/proposals/4

###
PATCH {{varBaseUrlPort}}/approvals/1
Content-Type: application/json

{
    "komen": "test"
}

###
# ini product
###
###
GET {{varBaseUrlPort}}/products

###
GET {{varBaseUrlPort}}/products/2

###
POST {{varBaseUrlPort}}/products
Content-Type: application/json

{
    "title": "Produk 2",
    "price": 555
}

###
PATCH {{varBaseUrlPort}}/products/3
Content-Type: application/json

{
    "title": "Produk 8",
    "price": 999
}

###
DELETE  {{varBaseUrlPort}}/products/4
